/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { InventarioDTO } from '../model/inventarioDTO';
import { StorageDTO } from '../model/storageDTO';
import { TransactionInventoryRequest } from '../model/transactionInventoryRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({providedIn: 'root'})
export class StorageControllerService {

    protected basePath = 'http://localhost:8088/ventimetriservice';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param productId
     * @param storageId
     * @param userName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addProduct(productId: number, storageId: number, userName: string, observe?: 'body', reportProgress?: boolean): Observable<InventarioDTO>;
    public addProduct(productId: number, storageId: number, userName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InventarioDTO>>;
    public addProduct(productId: number, storageId: number, userName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InventarioDTO>>;
    public addProduct(productId: number, storageId: number, userName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (productId === null || productId === undefined) {
            throw new Error('Required parameter productId was null or undefined when calling addProduct.');
        }

        if (storageId === null || storageId === undefined) {
            throw new Error('Required parameter storageId was null or undefined when calling addProduct.');
        }

        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling addProduct.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (productId !== undefined && productId !== null) {
            queryParameters = queryParameters.set('productId', <any>productId);
        }
        if (storageId !== undefined && storageId !== null) {
            queryParameters = queryParameters.set('storageId', <any>storageId);
        }
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('userName', <any>userName);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<InventarioDTO>('post',`${this.basePath}/api/storage/addproduct`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param branchCode
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addStorage(body: StorageDTO, branchCode: string, observe?: 'body', reportProgress?: boolean): Observable<StorageDTO>;
    public addStorage(body: StorageDTO, branchCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StorageDTO>>;
    public addStorage(body: StorageDTO, branchCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StorageDTO>>;
    public addStorage(body: StorageDTO, branchCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addStorage.');
        }

        if (branchCode === null || branchCode === undefined) {
            throw new Error('Required parameter branchCode was null or undefined when calling addStorage.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (branchCode !== undefined && branchCode !== null) {
            queryParameters = queryParameters.set('branchCode', <any>branchCode);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<StorageDTO>('post',`${this.basePath}/api/storage/create`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertDataIntoInventario(body: TransactionInventoryRequest, observe?: 'body', reportProgress?: boolean): Observable<StorageDTO>;
    public insertDataIntoInventario(body: TransactionInventoryRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StorageDTO>>;
    public insertDataIntoInventario(body: TransactionInventoryRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StorageDTO>>;
    public insertDataIntoInventario(body: TransactionInventoryRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling insertDataIntoInventario.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<StorageDTO>('put',`${this.basePath}/api/storage/insert/inventariodata`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param supplierId
     * @param storageId
     * @param userName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertProductsFromSupplierList(supplierId: number, storageId: number, userName: string, observe?: 'body', reportProgress?: boolean): Observable<Array<InventarioDTO>>;
    public insertProductsFromSupplierList(supplierId: number, storageId: number, userName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<InventarioDTO>>>;
    public insertProductsFromSupplierList(supplierId: number, storageId: number, userName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<InventarioDTO>>>;
    public insertProductsFromSupplierList(supplierId: number, storageId: number, userName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (supplierId === null || supplierId === undefined) {
            throw new Error('Required parameter supplierId was null or undefined when calling insertProductsFromSupplierList.');
        }

        if (storageId === null || storageId === undefined) {
            throw new Error('Required parameter storageId was null or undefined when calling insertProductsFromSupplierList.');
        }

        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling insertProductsFromSupplierList.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (supplierId !== undefined && supplierId !== null) {
            queryParameters = queryParameters.set('supplierId', <any>supplierId);
        }
        if (storageId !== undefined && storageId !== null) {
            queryParameters = queryParameters.set('storageId', <any>storageId);
        }
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('userName', <any>userName);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<InventarioDTO>>('post',`${this.basePath}/api/storage/insertsupplierproducts`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param inventarioId
     * @param insertedAmount
     * @param deletedAmount
     * @param userName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putData(inventarioId: number, insertedAmount: number, deletedAmount: number, userName: string, observe?: 'body', reportProgress?: boolean): Observable<InventarioDTO>;
    public putData(inventarioId: number, insertedAmount: number, deletedAmount: number, userName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InventarioDTO>>;
    public putData(inventarioId: number, insertedAmount: number, deletedAmount: number, userName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InventarioDTO>>;
    public putData(inventarioId: number, insertedAmount: number, deletedAmount: number, userName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (inventarioId === null || inventarioId === undefined) {
            throw new Error('Required parameter inventarioId was null or undefined when calling putData.');
        }

        if (insertedAmount === null || insertedAmount === undefined) {
            throw new Error('Required parameter insertedAmount was null or undefined when calling putData.');
        }

        if (deletedAmount === null || deletedAmount === undefined) {
            throw new Error('Required parameter deletedAmount was null or undefined when calling putData.');
        }

        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling putData.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (inventarioId !== undefined && inventarioId !== null) {
            queryParameters = queryParameters.set('inventarioId', <any>inventarioId);
        }
        if (insertedAmount !== undefined && insertedAmount !== null) {
            queryParameters = queryParameters.set('insertedAmount', <any>insertedAmount);
        }
        if (deletedAmount !== undefined && deletedAmount !== null) {
            queryParameters = queryParameters.set('deletedAmount', <any>deletedAmount);
        }
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('userName', <any>userName);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<InventarioDTO>('put',`${this.basePath}/api/storage/putdata`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param inventarioId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeProductFromStorage(inventarioId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public removeProductFromStorage(inventarioId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public removeProductFromStorage(inventarioId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public removeProductFromStorage(inventarioId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (inventarioId === null || inventarioId === undefined) {
            throw new Error('Required parameter inventarioId was null or undefined when calling removeProductFromStorage.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (inventarioId !== undefined && inventarioId !== null) {
            queryParameters = queryParameters.set('inventarioId', <any>inventarioId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/api/storage/delete/product`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param branchCode
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public retrieveStoragesByBranchCode(branchCode: string, observe?: 'body', reportProgress?: boolean): Observable<Array<StorageDTO>>;
    public retrieveStoragesByBranchCode(branchCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StorageDTO>>>;
    public retrieveStoragesByBranchCode(branchCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StorageDTO>>>;
    public retrieveStoragesByBranchCode(branchCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (branchCode === null || branchCode === undefined) {
            throw new Error('Required parameter branchCode was null or undefined when calling retrieveStoragesByBranchCode.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (branchCode !== undefined && branchCode !== null) {
            queryParameters = queryParameters.set('branchCode', <any>branchCode);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StorageDTO>>('get',`${this.basePath}/api/storage/retrieve/bybranchcode`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param storageId
     * @param userName
     * @param branchCode
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateStock(body: { [key: string]: number; }, storageId: number, userName: string, branchCode: string, observe?: 'body', reportProgress?: boolean): Observable<StorageDTO>;
    public updateStock(body: { [key: string]: number; }, storageId: number, userName: string, branchCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StorageDTO>>;
    public updateStock(body: { [key: string]: number; }, storageId: number, userName: string, branchCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StorageDTO>>;
    public updateStock(body: { [key: string]: number; }, storageId: number, userName: string, branchCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateStock.');
        }

        if (storageId === null || storageId === undefined) {
            throw new Error('Required parameter storageId was null or undefined when calling updateStock.');
        }

        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling updateStock.');
        }

        if (branchCode === null || branchCode === undefined) {
            throw new Error('Required parameter branchCode was null or undefined when calling updateStock.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<StorageDTO>('put',`${this.basePath}/api/storage/update/stock/${encodeURIComponent(String(storageId))}/${encodeURIComponent(String(userName))}/${encodeURIComponent(String(branchCode))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
