/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookingFormDto } from './bookingFormDto';
import { FormTag } from './formTag';

export interface BranchConfigurationDTO { 
    branchConfId?: number;
    branchCode?: string;
    guests?: number;
    bookingSlotInMinutes?: number;
    guestReceivingAuthConfirm?: number;
    minBeforeSendConfirmMessage?: number;
    maxTableNumber?: number;
    tags?: Array<FormTag>;
    instanceId?: string;
    displayName?: string;
    contactId?: string;
    formattedNumber?: string;
    profilePicUrl?: string;
    lastQrCode?: string;
    owner?: string;
    instanceCreationDate?: Date;
    instanceUpdateDate?: Date;
    instanceStatus?: string;
    message?: string;
    explanation?: string;
    lastWaApiConfCheck?: Date;
    branchConfCreationDate?: Date;
    bookingFormList?: Array<BookingFormDto>;
    dogsAllowed?: number;
    reservationConfirmedManually?: boolean;
}