/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';

export interface CreateBookingRequest { 
    branchCode?: string;
    formCode?: string;
    userEmail?: string;
    userPhone?: string;
    userName?: string;
    userLastName?: string;
    userDOB?: string;
    guests?: number;
    particularRequests?: string;
    date?: string;
    time?: LocalTime;
    treatmentPersonalData?: boolean;
}