/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CustomerDTO { 
    customerId?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    prefix?: string;
    birthDate?: Date;
    presenceCount?: number;
    origin?: string;
    lastPresence?: Date;
    flames?: number;
    address?: string;
    city?: string;
    province?: string;
    postalCode?: string;
    country?: string;
    privacyConsent?: boolean;
    marketingConsent?: boolean;
    profilingConsent?: boolean;
    emailSpamOptOut?: boolean;
    tags?: string;
    notes?: string;
    registrationDate?: Date;
}