/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EmployeeDTO { 
    employeeId?: number;
    lastName?: string;
    firstName?: string;
    gender?: EmployeeDTO.GenderEnum;
    jobDescription?: EmployeeDTO.JobDescriptionEnum;
    dob?: string;
    startDateInduction?: string;
    endDateInduction?: string;
    retribution?: number;
    contractType?: EmployeeDTO.ContractTypeEnum;
    email?: string;
    phone?: string;
    branchCode?: string;
    remunerationType?: EmployeeDTO.RemunerationTypeEnum;
    visible?: boolean;
    fired?: boolean;
}
export namespace EmployeeDTO {
    export type GenderEnum = 'UOMO' | 'DONNA';
    export const GenderEnum = {
        UOMO: 'UOMO' as GenderEnum,
        DONNA: 'DONNA' as GenderEnum
    };
    export type JobDescriptionEnum = 'AMMINISTRATORE' | 'ADDETTA_AL_MARKETING' | 'ADDETTO_ALL_ACCOGLIENZA_CLIENTI' | 'AIUTO_BARMAN' | 'AIUTO_CUOCO' | 'ADD_ALLA_CUCINA' | 'AIUTO_CAMERIERE' | 'BARMAN' | 'CAMERIERE_DI_BAR' | 'CAMERIERE' | 'CUOCO' | 'CUOCO_DI_RISTORANTE' | 'COORDINATRICE_DI_SALA' | 'COMMIS_DI_CUCINA' | 'DIRETTRICE_SALA_DEHORS' | 'FOOD_AND_BEVERAGE_MANAGER' | 'LAVAPIATTI' | 'PASTICCIERE' | 'PIZZAIOLO' | 'RESPONSABILE_DI_SALA' | 'TECNICI_WEB';
    export const JobDescriptionEnum = {
        AMMINISTRATORE: 'AMMINISTRATORE' as JobDescriptionEnum,
        ADDETTAALMARKETING: 'ADDETTA_AL_MARKETING' as JobDescriptionEnum,
        ADDETTOALLACCOGLIENZACLIENTI: 'ADDETTO_ALL_ACCOGLIENZA_CLIENTI' as JobDescriptionEnum,
        AIUTOBARMAN: 'AIUTO_BARMAN' as JobDescriptionEnum,
        AIUTOCUOCO: 'AIUTO_CUOCO' as JobDescriptionEnum,
        ADDALLACUCINA: 'ADD_ALLA_CUCINA' as JobDescriptionEnum,
        AIUTOCAMERIERE: 'AIUTO_CAMERIERE' as JobDescriptionEnum,
        BARMAN: 'BARMAN' as JobDescriptionEnum,
        CAMERIEREDIBAR: 'CAMERIERE_DI_BAR' as JobDescriptionEnum,
        CAMERIERE: 'CAMERIERE' as JobDescriptionEnum,
        CUOCO: 'CUOCO' as JobDescriptionEnum,
        CUOCODIRISTORANTE: 'CUOCO_DI_RISTORANTE' as JobDescriptionEnum,
        COORDINATRICEDISALA: 'COORDINATRICE_DI_SALA' as JobDescriptionEnum,
        COMMISDICUCINA: 'COMMIS_DI_CUCINA' as JobDescriptionEnum,
        DIRETTRICESALADEHORS: 'DIRETTRICE_SALA_DEHORS' as JobDescriptionEnum,
        FOODANDBEVERAGEMANAGER: 'FOOD_AND_BEVERAGE_MANAGER' as JobDescriptionEnum,
        LAVAPIATTI: 'LAVAPIATTI' as JobDescriptionEnum,
        PASTICCIERE: 'PASTICCIERE' as JobDescriptionEnum,
        PIZZAIOLO: 'PIZZAIOLO' as JobDescriptionEnum,
        RESPONSABILEDISALA: 'RESPONSABILE_DI_SALA' as JobDescriptionEnum,
        TECNICIWEB: 'TECNICI_WEB' as JobDescriptionEnum
    };
    export type ContractTypeEnum = 'DETERMINATO' | 'INDETERMINATO';
    export const ContractTypeEnum = {
        DETERMINATO: 'DETERMINATO' as ContractTypeEnum,
        INDETERMINATO: 'INDETERMINATO' as ContractTypeEnum
    };
    export type RemunerationTypeEnum = 'GIORNALIERA' | 'MENSILE' | 'ORARIA';
    export const RemunerationTypeEnum = {
        GIORNALIERA: 'GIORNALIERA' as RemunerationTypeEnum,
        MENSILE: 'MENSILE' as RemunerationTypeEnum,
        ORARIA: 'ORARIA' as RemunerationTypeEnum
    };
}