/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmployeeDTO } from './employeeDTO';

export interface EmployeePresenceReportDTO { 
    reportId?: number;
    branchCode?: string;
    employee?: EmployeeDTO;
    date?: Date;
    workedHours?: number;
    note?: string;
    presentAtLunch?: boolean;
    presentAtDinner?: boolean;
    holiday?: boolean;
    illness?: boolean;
    rest?: boolean;
}