/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HolidaysDTO } from './holidaysDTO';
import { OpeningHoursDTO } from './openingHoursDTO';
import { SpecialDayDTO } from './specialDayDTO';
import { TimeRange } from './timeRange';

export interface FormDTO { 
    formId?: number;
    formCode?: string;
    formName?: string;
    outputNameForCustomer?: string;
    branchCode?: string;
    branchName?: string;
    branchAddress?: string;
    redirectPage?: string;
    creationDate?: Date;
    formType?: FormDTO.FormTypeEnum;
    formStatus?: FormDTO.FormStatusEnum;
    logo?: Array<string>;
    regularOpeningHours?: Array<OpeningHoursDTO>;
    specialDays?: Array<SpecialDayDTO>;
    holidays?: Array<HolidaysDTO>;
    daylyTimeWorkingRange?: TimeRange;
    nightTimeWorkingRange?: TimeRange;
    cutterTimeForRanges?: number;
    maxGuests?: number;
    dogSizeThresholdKg?: number;
}
export namespace FormDTO {
    export type FormTypeEnum = 'PRENOTAZIONE' | 'RACCOLTA_DATI';
    export const FormTypeEnum = {
        PRENOTAZIONE: 'PRENOTAZIONE' as FormTypeEnum,
        RACCOLTADATI: 'RACCOLTA_DATI' as FormTypeEnum
    };
    export type FormStatusEnum = 'ATTIVO' | 'SOSPESO' | 'CANCELLATO';
    export const FormStatusEnum = {
        ATTIVO: 'ATTIVO' as FormStatusEnum,
        SOSPESO: 'SOSPESO' as FormStatusEnum,
        CANCELLATO: 'CANCELLATO' as FormStatusEnum
    };
}