/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeRange } from './timeRange';

export interface SpecialDayDTO { 
    id?: number;
    specialDayCode?: string;
    specialDate?: string;
    timeRanges?: Array<TimeRange>;
    description?: string;
    closed?: boolean;
}