/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StorageDTO } from './storageDTO';
import { SupplierDTO } from './supplierDTO';

export interface BranchResponseEntity { 
    branchId?: number;
    name?: string;
    address?: string;
    email?: string;
    phone?: string;
    vat?: string;
    type?: BranchResponseEntity.TypeEnum;
    branchCode?: string;
    role?: BranchResponseEntity.RoleEnum;
    logoImage?: Array<string>;
    authorized?: boolean;
    supplierDTOList?: Array<SupplierDTO>;
    storageDTOS?: Array<StorageDTO>;
}
export namespace BranchResponseEntity {
    export type TypeEnum = 'RISTORANTE' | 'FORNITORE' | 'CATERING';
    export const TypeEnum = {
        RISTORANTE: 'RISTORANTE' as TypeEnum,
        FORNITORE: 'FORNITORE' as TypeEnum,
        CATERING: 'CATERING' as TypeEnum
    };
    export type RoleEnum = 'AMMINISTRATORE' | 'RESPONSABILE' | 'FACTOTUM' | 'RESPONSABILE_MAGAZZINO' | 'BARMAN' | 'CUOCO' | 'CAMERIERE';
    export const RoleEnum = {
        AMMINISTRATORE: 'AMMINISTRATORE' as RoleEnum,
        RESPONSABILE: 'RESPONSABILE' as RoleEnum,
        FACTOTUM: 'FACTOTUM' as RoleEnum,
        RESPONSABILEMAGAZZINO: 'RESPONSABILE_MAGAZZINO' as RoleEnum,
        BARMAN: 'BARMAN' as RoleEnum,
        CUOCO: 'CUOCO' as RoleEnum,
        CAMERIERE: 'CAMERIERE' as RoleEnum
    };
}