/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateOrderEntity { 
    userName?: string;
    userCode?: string;
    branchCode?: string;
    insertedDate?: string;
    incomingDate?: string;
    preferredReceivingHour?: string;
    orderTarget?: CreateOrderEntity.OrderTargetEnum;
    branchCodeTarget?: string;
    supplierCodeTarget?: string;
    orderItemAmountMap?: { [key: string]: number; };
    thisOrderAlreadyInConsegnatoStatus?: boolean;
}
export namespace CreateOrderEntity {
    export type OrderTargetEnum = 'SUPPLIER' | 'BRANCH';
    export const OrderTargetEnum = {
        SUPPLIER: 'SUPPLIER' as OrderTargetEnum,
        BRANCH: 'BRANCH' as OrderTargetEnum
    };
}