/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';
import { OrderItemDto } from './orderItemDto';

export interface OrderDTO { 
    orderId?: number;
    createdByUser?: string;
    userCode?: string;
    createdBranchCode?: string;
    createdBranchName?: string;
    insertedDate?: string;
    incomingDate?: string;
    preferredReceivingTime?: LocalTime;
    orderStatus?: OrderDTO.OrderStatusEnum;
    orderTarget?: OrderDTO.OrderTargetEnum;
    codeTarget?: string;
    nameTarget?: string;
    orderItemDtoList?: Array<OrderItemDto>;
}
export namespace OrderDTO {
    export type OrderStatusEnum = 'BOZZA' | 'INVIATO' | 'IN_LAVORAZIONE' | 'PRONTO_A_PARTIRE' | 'DA_CONFERMARE' | 'CONSEGNATO' | 'ARCHIVIATO' | 'CANCELLATO';
    export const OrderStatusEnum = {
        BOZZA: 'BOZZA' as OrderStatusEnum,
        INVIATO: 'INVIATO' as OrderStatusEnum,
        INLAVORAZIONE: 'IN_LAVORAZIONE' as OrderStatusEnum,
        PRONTOAPARTIRE: 'PRONTO_A_PARTIRE' as OrderStatusEnum,
        DACONFERMARE: 'DA_CONFERMARE' as OrderStatusEnum,
        CONSEGNATO: 'CONSEGNATO' as OrderStatusEnum,
        ARCHIVIATO: 'ARCHIVIATO' as OrderStatusEnum,
        CANCELLATO: 'CANCELLATO' as OrderStatusEnum
    };
    export type OrderTargetEnum = 'SUPPLIER' | 'BRANCH';
    export const OrderTargetEnum = {
        SUPPLIER: 'SUPPLIER' as OrderTargetEnum,
        BRANCH: 'BRANCH' as OrderTargetEnum
    };
}