/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrderItemDto { 
    productId?: number;
    productName?: string;
    quantity?: number;
    receivedQuantity?: number;
    sentQuantity?: number;
    unitMeasure?: OrderItemDto.UnitMeasureEnum;
    price?: number;
    vatPrice?: number;
    vat?: number;
    received?: boolean;
    doneBySupplier?: boolean;
}
export namespace OrderItemDto {
    export type UnitMeasureEnum = 'KG' | 'PEZZI' | 'LITRI' | 'PACCHI' | 'BARATTOLIPICCOLI' | 'CARTONI' | 'CARTONE6' | 'CARTONE12' | 'CARTONE24' | 'CARTONE50' | 'BOTTIGLIA' | 'BARATTOLI' | 'FARDELLO' | 'CT' | 'BOTTIGLIETTA' | 'UNITA' | 'SECCHIO' | 'ALTRO' | 'COLLO';
    export const UnitMeasureEnum = {
        KG: 'KG' as UnitMeasureEnum,
        PEZZI: 'PEZZI' as UnitMeasureEnum,
        LITRI: 'LITRI' as UnitMeasureEnum,
        PACCHI: 'PACCHI' as UnitMeasureEnum,
        BARATTOLIPICCOLI: 'BARATTOLIPICCOLI' as UnitMeasureEnum,
        CARTONI: 'CARTONI' as UnitMeasureEnum,
        CARTONE6: 'CARTONE6' as UnitMeasureEnum,
        CARTONE12: 'CARTONE12' as UnitMeasureEnum,
        CARTONE24: 'CARTONE24' as UnitMeasureEnum,
        CARTONE50: 'CARTONE50' as UnitMeasureEnum,
        BOTTIGLIA: 'BOTTIGLIA' as UnitMeasureEnum,
        BARATTOLI: 'BARATTOLI' as UnitMeasureEnum,
        FARDELLO: 'FARDELLO' as UnitMeasureEnum,
        CT: 'CT' as UnitMeasureEnum,
        BOTTIGLIETTA: 'BOTTIGLIETTA' as UnitMeasureEnum,
        UNITA: 'UNITA' as UnitMeasureEnum,
        SECCHIO: 'SECCHIO' as UnitMeasureEnum,
        ALTRO: 'ALTRO' as UnitMeasureEnum,
        COLLO: 'COLLO' as UnitMeasureEnum
    };
}