/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionItem } from './transactionItem';

export interface TransactionInventoryRequest { 
    user?: string;
    storageId?: number;
    transactionItemList?: Array<TransactionItem>;
    operationType?: TransactionInventoryRequest.OperationTypeEnum;
}
export namespace TransactionInventoryRequest {
    export type OperationTypeEnum = 'CREATION' | 'INSERTION' | 'REMOVAL';
    export const OperationTypeEnum = {
        CREATION: 'CREATION' as OperationTypeEnum,
        INSERTION: 'INSERTION' as OperationTypeEnum,
        REMOVAL: 'REMOVAL' as OperationTypeEnum
    };
}